# Análisis de sensores industriales

Examen práctico — Manejo Masivo de Datos. Los datos del archivo `sensores_industriales.csv` son **simulados**. Umbral de alerta (regla didáctica del examen): temperatura mayor que 85 °C.

In [1]:
from pathlib import Path
import pandas as pd

umbral = 85
df = pd.read_csv(Path('data') / 'sensores_industriales.csv')
df.head()

,id_registro,fecha_hora,id_sensor,planta,temperatura_c,vibracion_mm_s
0,1,01/09/26 0:00,S001,Planta_1,65.93,1.40
1,2,01/09/26 0:00,S002,Planta_1,54.05,4.21
2,3,01/09/26 0:00,S003,Planta_1,66.34,2.26
3,4,01/09/26 0:00,S004,Planta_1,65.24,1.32
4,5,01/09/26 0:00,S005,Planta_1,68.12,3.22

## 1. Cantidad de registros y de sensores distintos

In [2]:
print('Registros:', len(df))
print('Sensores distintos:', df['id_sensor'].nunique())

Registros: 100000
Sensores distintos: 40

## 2. Temperatura promedio por planta

In [3]:
df.groupby('planta')['temperatura_c'].mean().round(2)

planta
Planta_1    66.62
Planta_2    66.53
Planta_3    66.77
Planta_4    66.67
Name: temperatura_c, dtype: float64

## 3. Temperatura máxima, sensor y fecha

Se muestran todos los registros empatados con el valor máximo.

In [4]:
tmax = df['temperatura_c'].max()
print('Temperatura máxima:', tmax)
df[df['temperatura_c'] == tmax][['id_sensor', 'fecha_hora', 'temperatura_c']].head(10)

Temperatura máxima: 104.99

      id_sensor      fecha_hora  temperatura_c
53742      S023  01/09/26 22:23         104.99
89258      S019  02/09/26 13:11         104.99
94533      S014  02/09/26 15:23         104.99
96109      S030  02/09/26 16:02         104.99

## 4. Lecturas con temperatura mayor que 85 °C

In [5]:
alertas = df[df['temperatura_c'] > umbral]
print('Alertas de temperatura:', len(alertas))

Alertas de temperatura: 6954

## 5. Planta con más alertas

Si hay empate se muestran todas las plantas empatadas.

In [6]:
conteo = alertas['planta'].value_counts()
print(conteo)
conteo[conteo == conteo.max()]

planta
Planta_3    1777
Planta_1    1737
Planta_4    1732
Planta_2    1708
Name: count, dtype: int64

planta
Planta_3    1777
Name: count, dtype: int64

## 6. Exportar alertas a `resultados/alertas.csv`

In [7]:
Path('resultados').mkdir(exist_ok=True)
alertas.to_csv(Path('resultados') / 'alertas.csv', index=False)
pd.read_csv(Path('resultados') / 'alertas.csv').head()

,id_registro,fecha_hora,id_sensor,planta,temperatura_c,vibracion_mm_s
0,7,01/09/26 0:00,S007,Planta_1,97.65,5.45
1,21,01/09/26 0:00,S021,Planta_3,86.35,2.87
2,40,01/09/26 0:00,S040,Planta_4,98.48,4.11
3,50,01/09/26 0:01,S010,Planta_1,97.99,4.49
4,53,01/09/26 0:01,S013,Planta_2,85.02,3.33